<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Tasks Application')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ?>

        <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
        ?>
    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <?php if ($this->aclHelper()->isPermitted('Application\Controller\IndexController_index')):?>
                        <a class="navbar-brand" href="<?php echo $this->url('home');?>">
                            &nbsp;Tasks application
                        </a>
                    <?php endif;?>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <?php if ($this->aclHelper()->isPermitted('Application\Controller\IndexController_index')):?>
                            <li class=""><a href="<?php echo $this->url('home');?>">Home</a></li>
                        <?php endif;?>
                        <?php if ($this->aclHelper()->isPermitted('Application\Controller\TaskController_userTasks')):?>
                            <li class=""><a href="<?php echo $this->url('user.tasks');?>">Tasks</a></li>
                        <?php endif;?>
                        <?php if ($this->aclHelper()->isPermitted('Application\Controller\AdminController_index')):?>
                            <li class=""><a href="<?php echo $this->url('admin.index');?>">Administration</a></li>
                        <?php endif;?>
                        <?php if ($this->aclHelper()->isPermitted('Application\Controller\AuthController_logout')):?>
                            <li class=""><a href="<?php echo $this->url('user.logout');?>">Logout</a></li>
                        <?php endif;?>
                    </ul>
                </div>
            </div>
        </nav>
        <div class="container">
            <div class="row">
                <div class="col-lg-6 col-lg-offset-3">
                    <?= $this->content ?>
                    <hr>
                    <footer>
                        <p>&copy; 2018 - <?= date('Y') ?> by Yordan Kirovski. All rights reserved.</p>
                    </footer>
                <div>
            <div>
        </div>
        <?= $this->inlineScript() ?>
    </body>
</html>
