<?php
    $form = $this->form;
    $form->setAttribute('action', $this->url('tasks.add', ['userTaskListID' => $this->userTaskListID]));
    $form->prepare();
?>

<div class="row">
    <div class="col-md-12">
        <?php echo $this->flashMessenger()->renderCurrent('error', ['alert', 'alert-danger', 'list-unstyled']);?>
        
        <?php echo $this->form()->openTag($form); ?>

        <div class="form-group">
            <?php echo $this->formLabel($form->get('taskText')); ?>
            <?php echo $this->formElement($form->get('taskText')); ?>
            <?php echo $this->formElementErrors($form->get('taskText'), array('class' => 'alert alert-danger list-unstyled')); ?>
        </div>

        <?php echo $this->form()->closeTag(); ?>
    </div>
</div>
