<?php
    $form = $this->form;
    $form->setAttribute('action', $this->url('tasks.add', ['userTaskListID' => $this->userTaskListID]));
    $form->prepare();
?>

<div class="row">
    <div class="col-md-12">
        <?php echo $this->flashMessenger()->renderCurrent('error', ['alert', 'alert-danger', 'list-unstyled']);?>
        
        <?php echo $this->form()->openTag($form); ?>

        <div class="form-group">
            <?php echo $this->formLabel($form->get('taskText')); ?>
            <?php echo $this->formElement($form->get('taskText')); ?>
            <?php echo $this->formElementErrors($form->get('taskText'), array('class' => 'alert alert-danger list-unstyled')); ?>
        </div>

        <?php // echo $this->formElement($form->get('submit')); ?>

        <?php echo $this->form()->closeTag(); ?>
    </div>
</div>


<?php if (empty($this->ajaxRequest) || !$this->ajaxRequest):?>
    <script type="text/javascript">
        jQuery(document).ready(function() {
//            jQuery(document).on('click', '#addTaskButton', function(event) {
//                event.preventDefault();
//                event.stopPropagation();
//                
//                var formActionUrl = jQuery("#add-task-form").attr('action');
//                var formData = jQuery("#add-task-form").serialize();
//
//                jQuery.ajax(
//                    {
//                        type: "POST",
//                        url: formActionUrl,
//                        data: formData,
//                        success: function(data) {
//                            if (typeof data.redirectUrl != 'undefined' && data.status) {
//                                window.location = data.redirectUrl;
//                            } else if (typeof data.content != 'undefined') {
//                                jQuery('#createTaskContainer').html(data.content);
//                            }
//                        },
//                        error: function(data) {
//                            if (typeof data.message != 'undefined') {
////                                jQuery('#errorMessage').html(data.message);
//                            }
//                        },
//                        complete : function(data) {
//
//                        }
//                    }
//                );
//
//                return;
//            });
        });
    </script>
<?php endif;?>

